DROP TABLE address CASCADE;
DROP TABLE contact CASCADE;
DROP TABLE illness CASCADE;
DROP TABLE medical_card CASCADE;
DROP TABLE person_data CASCADE;
DROP TABLE user CASCADE;
DROP TABLE role CASCADE;
DROP TABLE user_role CASCADE;